/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#ffd4c4",
        "inverse-primary": "#a5d0b9",
        "surface-tint": "#3f6653",
        "primary-fixed-dim": "#a5d0b9",
        "error": "#ba1a1a",
        "outline": "#717973",
        "inverse-on-surface": "#f3f0ed",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#e7beae",
        "on-secondary-fixed": "#2c160c",
        "on-tertiary-fixed-variant": "#623f18",
        "background": "#fcf9f6",
        "primary-fixed": "#c1ecd4",
        "tertiary": "#3b1f00",
        "primary": "#012d1d",
        "on-surface": "#1c1c1a",
        "surface-dim": "#dcd9d7",
        "outline-variant": "#c1c8c2",
        "secondary": "#77574b",
        "surface-variant": "#e5e2df",
        "surface-container": "#f0edea",
        "surface-container-high": "#eae8e5",
        "on-surface-variant": "#414844",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#2c1600",
        "surface-container-highest": "#e5e2df",
        "surface-bright": "#fcf9f6",
        "tertiary-container": "#56340e",
        "tertiary-fixed": "#ffdcbd",
        "on-primary-fixed": "#002114",
        "on-tertiary-container": "#cd9d6d",
        "on-secondary": "#ffffff",
        "on-primary-container": "#86af99",
        "error-container": "#ffdad6",
        "on-background": "#1c1c1a",
        "on-secondary-fixed-variant": "#5d4034",
        "surface-container-low": "#f6f3f0",
        "surface": "#fcf9f6",
        "on-primary-fixed-variant": "#274e3d",
        "on-error": "#ffffff",
        "on-secondary-container": "#7a594d",
        "tertiary-fixed-dim": "#f0bd8b",
        "secondary-fixed": "#ffdbce",
        "primary-container": "#1b4332",
        "inverse-surface": "#31302f"
      },
      borderRadius: {
        "xl": "1.5rem",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
